FROM ubuntu:xenial
ENV container=docker

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libffi-dev \
    libssl-dev python-dev python-minimal python-pip python-setuptools \
    python-virtualenv

RUN pip install ansible ansible-lint ipaddress wheel

COPY .ansible-lint /
