FROM debian:stretch
ENV container=docker

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libffi-dev \
    libssl-dev python-dev python-minimal python-pip python-setuptools \
    python-virtualenv systemd

RUN pip install --upgrade pip setuptools && \
    pip install ansible ansible-lint enum34 ipaddress wheel

COPY .ansible-lint /
